name: Conventional Commits

on:
  push:

jobs:
  conventional-commits:
    name: Conventional Commits
    runs-on: ubuntu-latest
    steps:
<<<<<<< HEAD
      - uses: actions/checkout@v4
=======
      - uses: actions/checkout@v3
>>>>>>> template/main
      - uses: ubiquity/action-conventional-commits@master
