name: Knip

on:
  pull_request:

jobs:
  run-knip:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # needed to use yarn v4
      - name: Enable corepack
        run: corepack enable

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20.10.0

      - name: Install toolchain
        run: yarn install

      - name: Store PR number
        run: echo ${{ github.event.number }} > pr-number.txt

      - name: Run Knip
        run: yarn knip --no-exit-code || yarn knip --reporter json > knip-results.json
        env: # Set environment variables for the build
          SUPABASE_URL: "https://wfzpewmlyiozupulbuur.supabase.co"
          SUPABASE_ANON_KEY: "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndmenBld21seWlvenVwdWxidXVyIiwicm9sZSI6ImFub24iLCJpYXQiOjE2OTU2NzQzMzksImV4cCI6MjAxMTI1MDMzOX0.SKIL3Q0NOBaMehH0ekFspwgcu3afp3Dl9EDzPqs1nKs"

      - name: Upload knip result
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: knip-results
          path: |
            knip-results.json
            pr-number.txt
